analysis_metrics:
  default:
    - id: new_lines
      source: Sonar

    - id: new_coverage
      source: Sonar

    - id: files
      source: Sonar

  radar:
    - id: cyclomatic_complexity
      checked: false
      source: CodeQL
      thresholds:
        a:
          lower_bound: 0
          upper_bound: 5
        b:
          lower_bound: 5
          upper_bound: 10
        c:
          lower_bound: 10
          upper_bound: 20
        d:
          lower_bound: 20
          upper_bound: 80
        e:
          lower_bound: 80
          upper_bound: 100  # Upper limit is +15

    - id: cognitive_complexity
      checked: true
      source: Sonar
      thresholds:
        a:
          lower_bound: 0
          upper_bound: 5
        b:
          lower_bound: 5
          upper_bound: 10
        c:
          lower_bound: 10
          upper_bound: 20
        d:
          lower_bound: 20
          upper_bound: 30
        e:
          lower_bound: 30
          upper_bound: 40  # Upper limit is +15

    - id: instability
      checked: false
      source: CodeQL
      thresholds:
        a:
          lower_bound: 0
          upper_bound: 0.2
        b:
          lower_bound: 0.2
          upper_bound: 0.4
        c:
          lower_bound: 0.4
          upper_bound: 0.6
        d:
          lower_bound: 0.6
          upper_bound: 0.8
        e:
          lower_bound: 0.8
          upper_bound: 1  # Upper limit is 100%

    - id: lack_of_cohesion
      checked: false
      source: CodeQL
      thresholds:
        a:
          lower_bound: 0
          upper_bound: 5
        b:
          lower_bound: 5
          upper_bound: 10
        c:
          lower_bound: 10
          upper_bound: 20
        d:
          lower_bound: 20
          upper_bound: 80
        e:
          lower_bound: 80
          upper_bound: 100  # Upper limit is +15
